# config for Django + Postgres -> Travis -> Heroku

language: python
python:
    - 3.6
services:
#    - docker
    - postgresql
install:
    - pip install -r requirements.txt
#before_script:
#    - python manage.py collectstatic
#    - psql -c 'create database testdb;' -U postgres
#    - psql -c 'create database travisci;' -U postgres
#    - psql -c "CREATE DATABASE testdb;" -U postgres

script:
#    - docker-compose build
#    - docker ps
#    - docker-compose run web python manage.py test
#    - docker-compose run web python manage.py makemigrations
#    - docker-compose run web python manage.py migrate
    # travis without dockerization
#    - python manage.py makemigrations
#    - python manage.py migrate
    - python manage.py test

# undockerize, travis CI straight to heroku deployment CD
deploy:
    provider: heroku
    api_key: $HEROKU_API_KEY
    app: webapp-dpth
    run: python manage.py migrate
    on: master
